[project]
name = "Customer_Churn_Prediction_Group_06"
version = "1.0.0"
description = "project aims to predict customer churn"
authors = [
    {name = "Ganindu-Deshapriya", email = "ganindudeshapriya@gmail.com"}
]
requires-python = ">=3.9"
